name: Calendar Event Submission
description: Submit an event for the Mako Parents calendar (goes to approval)
title: "[Calendar] Event: <short title>"
labels:
  - calendar-event
  - needs-approval
body:
  - type: input
    id: title
    attributes:
      label: Event Name
      placeholder: "e.g., Football vs. Gulf Shores"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Event Date (YYYY-MM-DD)
      placeholder: "2025-09-15"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: Event Time (24h HH:MM) — leave blank for all-day
      placeholder: "19:00"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Event Description
      placeholder: "Key details parents should know…"
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Event Location (optional)
      placeholder: "OBHS Stadium"
    validations:
      required: false

  - type: input
    id: link
    attributes:
      label: Event Link (tickets/info) (optional)
      placeholder: "https://..."
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - school
        - sports
        - testing
        - deadlines
        - arts
        - community
      default: 0
    validations:
      required: true

  - type: input
    id: contact_name
    attributes:
      label: Event Contact Name
      placeholder: "First Last"
    validations:
      required: false

  - type: input
    id: contact_phone
    attributes:
      label: Event Contact Phone Number
      placeholder: "251-555-1234"
    validations:
      required: false

  - type: input
    id: contact_email
    attributes:
      label: Event Contact Email
      placeholder: "name@example.com"
    validations:
      required: false
