name: Approve calendar submission

on:
  issues:
    types: [labeled, edited, reopened]
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  approve:
    # Only run when the issue has the label Approved (case-sensitive to your label name)
    if: contains(github.event.issue.labels.*.name, 'Approved')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure data file exists
        run: |
          mkdir -p data
          if [ ! -f data/events.json ]; then
            echo '[]' > data/events.json
          fi

      - name: Append event to events.json
        run: |
          node -e "
          const fs = require('fs');
          const path = 'data/events.json';
          const events = JSON.parse(fs.readFileSync(path,'utf8'));
          const body = process.env.ISSUE_BODY || '';
          const title = process.env.ISSUE_TITLE || 'Untitled';

          const get = (label) => {
            const m = body.match(new RegExp(label+':\\s*(.+)','i'));
            return m ? m[1].trim() : '';
          };

          const event = {
            title: get('Event Name') || title,
            date:  get('Event Date'),
            time:  get('Event Time'),
            description: get('Event Description'),
            contact: get('Event Contact'),
            phone: get('Event Contact Phone Number') || get('Phone'),
            email: get('Event Contact Email') || get('Email'),
            sourceIssue: process.env.ISSUE_URL
          };

          if (!event.title || !event.date) {
            console.error('Missing title or date; refusing to append.');
            process.exit(1);
          }

          events.push(event);
          fs.writeFileSync(path, JSON.stringify(events, null, 2));
          console.log('Appended', event);
          "
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/events.json
          git commit -m "chore(calendar): approve issue #${{ github.event.issue.number }}" || echo "No changes"
          git push
