      - name: Ensure events file exists
        run: |
          mkdir -p calendar
          if [ ! -f calendar/events.json ]; then
            echo '[]' > calendar/events.json
          fi

      - name: Append event to events.json
        run: |
          node -e "
          const fs = require('fs');
          const path = 'calendar/events.json';   // <<-- updated path
          const body = process.env.ISSUE_BODY || '';
          const titleRaw = process.env.ISSUE_TITLE || 'Untitled';

          if (!fs.existsSync('calendar')) fs.mkdirSync('calendar');
          if (!fs.existsSync(path)) fs.writeFileSync(path, '[]');

          const events = JSON.parse(fs.readFileSync(path,'utf8'));

          const get = (label) => {
            const m = body.match(new RegExp(label+':\\s*(.+)','i'));
            return m ? m[1].trim() : '';
          };

          const event = {
            title: get('Event Name') || titleRaw,
            date: get('Event Date'),
            time: get('Event Time'),
            description: get('Event Description'),
            contact: get('Event Contact'),
            phone: get('Event Contact Phone Number') || get('Phone'),
            email: get('Event Contact Email') || get('Email'),
            sourceIssue: process.env.ISSUE_URL
          };

          if (!event.title || !event.date) {
            console.error('Missing title or date; refusing to append.');
            process.exit(1);
          }

          events.push(event);
          fs.writeFileSync(path, JSON.stringify(events,null,2));
          console.log('Appended event:', event);
          "
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
