name: Build calendar events
on:
  schedule:
    - cron: "17 2 * * *"   # runs nightly ~2:17am UTC
  workflow_dispatch: {}     # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm init -y
          npm install ical node-fetch@2

      - name: Build events.json
        run: node tools/build-events.mjs

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add calendar/events.json package.json package-lock.json
            git commit -m "chore(calendar): refresh events.json"
            git push
          else
            echo "No changes"
          fi
