name: Notify new calendar submission
on:
  issues:
    types: [opened, edited]
permissions:
  contents: read
  issues: write

jobs:
  notify:
    if: contains(github.event.issue.labels.*.name, 'calendar-event')
    runs-on: ubuntu-latest
    steps:
      - name: Ensure labels exist & keep "needs-approval"
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const need = 'needs-approval';
            // ensure label exists (no-op if already there)
            try {
              await github.rest.issues.getLabel({owner, repo, name: need});
            } catch {
              await github.rest.issues.createLabel({owner, repo, name: need, color: 'f0ad4e', description: 'Pending review'});
            }
            // make sure the issue has the label
            await github.rest.issues.addLabels({
              owner, repo, issue_number: context.payload.issue.number, labels: [need]
            });

      - name: Build email content from Issue Form
        id: build
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            // Issue Forms render as a table; pull values by field label
            function get(field){
              const re = new RegExp(`\\|\\s*${field}\\s*\\|([^\\n]+)\\n`);
              const m = issue.body.match(re);
              return m ? m[1].trim().replace(/^:/,'').trim() : '';
            }
            const title    = get('Event title');
            const date     = get('Date (YYYY-MM-DD)');
            const time     = get('Start time \\(24h HH:MM\\) — leave blank for all-day');
            const category = get('Category');
            const location = get('Location \\(optional\\)');
            const link     = get('Link \\(tickets/info\\) \\(optional\\)');
            const notes    = get('Details \\(optional\\)');

            const subject = `[Mako Parents] NEW submission: ${title || '(no title)'} (${date}${time? ' ' + time : ''})`;
            const approveUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/issues/${issue.number}`;
            const body = [
              `New calendar submission awaiting approval:`,
              ``,
              `Title: ${title}`,
              `Date: ${date}`,
              `Time: ${time || '(all-day)'}`,
              `Category: ${category}`,
              `Location: ${location || '(none)'}`,
              `Link: ${link || '(none)'}`,
              `Details: ${notes || '(none)'}`,
              ``,
              `Approve by opening this link and adding the "approved" label:`,
              approveUrl
            ].join('\n');

            core.setOutput('subject', subject);
            core.setOutput('body', body);

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ steps.build.outputs.subject }}
          to: ${{ secrets.NOTIFY_TO }}
          from: "${{ secrets.FROM_NAME || 'Mako Parents' }} <${{ secrets.SMTP_USERNAME }}>"
          body: ${{ steps.build.outputs.body }}
