name: Notify on new calendar submission

on:
  issues:
    types: [opened, edited, reopened, labeled]
  workflow_dispatch:  # manual trigger for testing

jobs:
  notify:
    # Don't over-filter at the job level; keep it simple
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "New Calendar Submission: ${{ github.event.issue.title }}"
          to: ${{ secrets.TO_EMAIL }}
          from: "Mako Parents <${{ secrets.SMTP_USERNAME }}>"
          secure: true
          charset: utf-8
          html_body: |
            <p>A new calendar event was submitted:</p>
            <p><a href='${{ github.event.issue.html_url }}'>View Issue #${{ github.event.issue.number }}</a></p>
            <pre>${{ github.event.issue.body }}</pre>
